[build]
  command = "hugo -c ./exampleSite/content/ --config ./exampleSite/config.toml --baseURL https://clever-visvesvaraya-e41cfa.netlify.com/ -t ''"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "false"